test using GITHUB_PATH

diff --git a/.github/workflows/openssl-win32.yml b/.github/workflows/openssl-win32.yml
--- a/.github/workflows/openssl-win32.yml
+++ b/.github/workflows/openssl-win32.yml
@@ -34,21 +34,21 @@ jobs:
         shell: pwsh
         run: choco install strawberryperl nasm -y
         
-      #- name: Add choco bin to PATH
-      #  shell: cmd
-      #  run: echo C:\ProgramData\chocolatey\bin >> %GITHUB_PATH%
-      
-      - name: Debug Find nasm via CMD
+      - name: Add choco bin to PATH
         shell: cmd
-        run: |
-          echo Searching for nasm.exe on C: drive...
-          where /R C:\ nasm.exe || echo "nasm not found"
+        run: echo "C:\Program Files\NASM" >> %GITHUB_PATH%
+      
+      #- name: Debug Find nasm via CMD
+      #  shell: cmd
+      #  run: |
+      #    echo Searching for nasm.exe on C: drive...
+      #    where /R C:\ nasm.exe || echo "nasm not found"
 
       - name: Setup environment and compile test install
         shell: cmd
         run: |
           call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
-          set PATH=C:\ProgramData\chocolatey\bin;%PATH%
+          #set PATH=C:\ProgramData\chocolatey\bin;%PATH%
           cd openssl-src
           perl Configure VC-WIN32 --prefix=%CD%\openssl-install
           nmake
